// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTSxm1oeOGJ3Ywo4WB_VLy9SqnfXF1OL8',
    appId: '1:330079705329:web:92a94d1d024d53eeacb150',
    messagingSenderId: '330079705329',
    projectId: 'pings-and-pulls',
    authDomain: 'pings-and-pulls.firebaseapp.com',
    storageBucket: 'pings-and-pulls.firebasestorage.app',
    measurementId: 'G-4GCGRDDWDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYOtaOlFYxm68vjszRPNz4nhp-mZtQpQ0',
    appId: '1:330079705329:android:f4d32ac0651109ccacb150',
    messagingSenderId: '330079705329',
    projectId: 'pings-and-pulls',
    storageBucket: 'pings-and-pulls.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmVQ0jBPYwMOBZD4S6Ew1yMXIQI8ty7gc',
    appId: '1:330079705329:ios:cbc74ce5cabd0cd7acb150',
    messagingSenderId: '330079705329',
    projectId: 'pings-and-pulls',
    storageBucket: 'pings-and-pulls.firebasestorage.app',
    iosBundleId: 'com.example.pingsAndPulls',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmVQ0jBPYwMOBZD4S6Ew1yMXIQI8ty7gc',
    appId: '1:330079705329:ios:cbc74ce5cabd0cd7acb150',
    messagingSenderId: '330079705329',
    projectId: 'pings-and-pulls',
    storageBucket: 'pings-and-pulls.firebasestorage.app',
    iosBundleId: 'com.example.pingsAndPulls',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTSxm1oeOGJ3Ywo4WB_VLy9SqnfXF1OL8',
    appId: '1:330079705329:web:c8699a29fbc727c9acb150',
    messagingSenderId: '330079705329',
    projectId: 'pings-and-pulls',
    authDomain: 'pings-and-pulls.firebaseapp.com',
    storageBucket: 'pings-and-pulls.firebasestorage.app',
    measurementId: 'G-FE0R4Y38EN',
  );
}
